name: mimia
description: MiMia app

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.6.5
  cloud_firestore: ^5.8.0
  firebase_storage: ^11.3.0
  just_audio: ^0.9.39
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
